.PHONY: clean All

All:
	@echo "----------Building project:[ MAIN - Debug ]----------"
	@cd "MAIN" && "$(MAKE)" -f  "MAIN.mk"
clean:
	@echo "----------Cleaning project:[ MAIN - Debug ]----------"
	@cd "MAIN" && "$(MAKE)" -f  "MAIN.mk" clean
